on:
  push:
    branches:
      - master
  pull_request:

name: Build and bundle
jobs:
  chore:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Print environment
        run: |
          node --version
          npm --version
          python --version
          pip --version

      - name: Install Node dependencies
        run: npm ci

      - name: Compile with TypeScript
        run: npm run build

      - name: Bundle with Rollup
        run: npm run dist
